[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "modpack-changelogger"
version = "1.0.1"
description = "A powerful and customizable Python tool to generate a changelog between two Minecraft modpacks in modrinth.mrpack or curseforge.zip format."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "TheBossMagnus", email = "thebossmagnus@proton.me"}
]
urls = { "Homepage" = "https://github.com/TheBossMagnus/ModpackChangelogger" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = ["aiohttp>=3.9.5"]

[project.scripts]
modpack-changelogger = "modpack_changelogger:cli_wrapper.wrapper"

[tool.setuptools.packages.find]
where = ["modpack_changelogger"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.ruff]
line-length = 100
select = ["E", "F", "W", "C90"]
ignore = ["E501"]
exclude = ["tests/*"]