name: Build with PyInstaller on Commit

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          uv pip install pyinstaller

      - name: Get commit SHA
        id: commit_sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --icon=NONE --name modpack-changelogger-${{ env.sha }} modpack_changelogger/__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modpack Changelogger-${{ env.sha }}
          path: dist/modpack-changelogger*
