on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller aiohttp setuptools wheel build twine

    - name: Get commit SHA
      id: commit_sha
      run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
      shell: bash

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --icon=NONE --name ModpackChangelogger-${{ env.sha }} modpack_changelogger.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Modpack-Changelogger-${{ env.sha }}
        path: dist/ModpackChangelogger*
    
    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      run: |
        python -m pip install twine
        twine upload dist/*