name: Build and Publish Modpack Changelogger Executable on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          uv pip install pyinstaller

      - name: Get commit SHA
        id: commit_sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --icon=NONE --name modpack-changelogger-${{github.event.release.tag_name}} modpack_changelogger/__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modpack Changelogger-${{github.event.release.tag_name}}
          path: dist/modpack-changelogger*

      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/modpack-changelogger-${{github.event.release.tag_name}}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
