name: Build and Publish Modpack Changelogger Executable on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Get commit SHA
        id: commit_sha
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --icon=NONE --name modpack-changelogger-${{github.event.release.tag_name}} modpack_changelogger/__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Modpack Changelogger-${{github.event.release.tag_name}}
          path: dist/modpack-changelogger*

      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/modpack-changelogger-${{github.event.release.tag_name}}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
